const reports = {
  chesapeake: [
    {
      species: 'Striped Bass',
      location: 'Upper Chesapeake Bay',
      zone: 'upper-bay',
      date: new Date().toISOString(),
      technique: 'Live herring, deep structure',
      weight: '18-28 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Striped Bass',
      location: 'Eastern Bay Lumps',
      zone: 'upper-bay',
      date: new Date(Date.now() - 1800000).toISOString(),
      technique: 'Topwater at dawn',
      weight: '20-26 lbs',
      action: 'Very Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Largemouth Bass',
      location: 'Eastern Bay',
      zone: 'middle-bay',
      date: new Date(Date.now() - 3600000).toISOString(),
      technique: 'Crankbaits, shallow grass',
      weight: '3-5 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Perch',
      location: 'Eastern Bay Flats',
      zone: 'middle-bay',
      date: new Date(Date.now() - 5400000).toISOString(),
      technique: 'Small jigs, live shiners',
      weight: '1-2 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Bluefish',
      location: 'Lower Bay',
      zone: 'lower-bay',
      date: new Date(Date.now() - 7200000).toISOString(),
      technique: 'Metal shad lures',
      weight: '6-10 lbs',
      action: 'Very Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Striped Bass',
      location: 'Sandy Point',
      zone: 'lower-bay',
      date: new Date(Date.now() - 9000000).toISOString(),
      technique: 'Live eels at dusk',
      weight: '15-22 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
  ],
  potomac: [
    {
      species: 'Smallmouth Bass',
      location: 'Sycamore Island',
      zone: 'upper-potomac',
      date: new Date().toISOString(),
      technique: 'Tube jigs on structure',
      weight: '2-4 lbs',
      action: 'Very Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Smallmouth Bass',
      location: 'Great Falls',
      zone: 'upper-potomac',
      date: new Date(Date.now() - 1800000).toISOString(),
      technique: 'Crankbaits in current',
      weight: '2-3 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Striped Bass',
      location: 'Monitor Run',
      zone: 'middle-potomac',
      date: new Date(Date.now() - 3600000).toISOString(),
      technique: 'Live herring in current',
      weight: '16-22 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Channel Catfish',
      location: 'Roosevelt Island',
      zone: 'middle-potomac',
      date: new Date(Date.now() - 5400000).toISOString(),
      technique: 'Cut shad, night fishing',
      weight: '10-18 lbs',
      action: 'Excellent',
      source: 'Maryland DNR',
    },
    {
      species: 'Striped Bass',
      location: 'Occoquan',
      zone: 'lower-potomac',
      date: new Date(Date.now() - 7200000).toISOString(),
      technique: 'Topwater plugs at dawn',
      weight: '14-20 lbs',
      action: 'Very Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Largemouth Bass',
      location: 'Pohick Bay',
      zone: 'lower-potomac',
      date: new Date(Date.now() - 9000000).toISOString(),
      technique: 'Spinnerbaits in grass',
      weight: '2-4 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
  ],
  paxriver: [
    {
      species: 'Largemouth Bass',
      location: 'Hunting Creek',
      zone: 'upper-pax',
      date: new Date().toISOString(),
      technique: 'Soft plastics in vegetation',
      weight: '3-5 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Bluegill',
      location: 'Upper Patuxent',
      zone: 'upper-pax',
      date: new Date(Date.now() - 1800000).toISOString(),
      technique: 'Crickets and worms',
      weight: '0.5-1 lb',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Channel Catfish',
      location: 'Jug Bay',
      zone: 'middle-pax',
      date: new Date(Date.now() - 3600000).toISOString(),
      technique: 'Cut shad at dusk',
      weight: '15-25 lbs',
      action: 'Excellent',
      source: 'Maryland DNR',
    },
    {
      species: 'Largemouth Bass',
      location: 'Jug Bay Marsh',
      zone: 'middle-pax',
      date: new Date(Date.now() - 5400000).toISOString(),
      technique: 'Topwater in lily pads',
      weight: '4-6 lbs',
      action: 'Very Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Largemouth Bass',
      location: 'Benedict area',
      zone: 'lower-pax',
      date: new Date(Date.now() - 7200000).toISOString(),
      technique: 'Soft plastics in weeds',
      weight: '3-5 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
    {
      species: 'Catfish',
      location: 'Lower Patuxent',
      zone: 'lower-pax',
      date: new Date(Date.now() - 9000000).toISOString(),
      technique: 'Chicken liver at night',
      weight: '8-15 lbs',
      action: 'Good',
      source: 'Maryland DNR',
    },
  ],
};